platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/CocoaPods/Specs.git'

target 'Flic2Example' do
  
 config = use_native_modules!
 permissions_path = '../node_modules/react-native-permissions/ios'
 pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"

 use_react_native!(:path => config["reactNativePath"])
  
end
